version: "3.9"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM=xinference
      - EMBEDDING=xinference
    devices:
      - /dev/nvidia0:/dev/nvidia0